import { db } from '@/db';
import { songs } from '@/db/schema';

async function main() {
    const sampleSongs = [
        // The Midnight Echo - Electronic/Indie (from "Neon Dreams" album)
        {
            title: 'Midnight Runner',
            artistName: 'The Midnight Echo',
            albumName: 'Neon Dreams',
            durationSeconds: 245,
            coverImageUrl: '/images/songs/song-1.jpg',
            audioUrl: '/audio/song-1.mp3',
            playCount: 125000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Digital Dreams',
            artistName: 'The Midnight Echo',
            albumName: 'Neon Dreams',
            durationSeconds: 267,
            coverImageUrl: '/images/songs/song-2.jpg',
            audioUrl: '/audio/song-2.mp3',
            playCount: 98000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'City Lights',
            artistName: 'The Midnight Echo',
            albumName: 'Neon Dreams',
            durationSeconds: 234,
            coverImageUrl: '/images/songs/song-3.jpg',
            audioUrl: '/audio/song-3.mp3',
            playCount: 87500,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Echo Chamber',
            artistName: 'The Midnight Echo',
            albumName: null,
            durationSeconds: 198,
            coverImageUrl: '/images/songs/song-4.jpg',
            audioUrl: '/audio/song-4.mp3',
            playCount: 15000,
            createdAt: new Date().toISOString(),
        },

        // Luna Park - Pop (from "Cosmic Journey" album)
        {
            title: 'Starlight Boulevard',
            artistName: 'Luna Park',
            albumName: 'Cosmic Journey',
            durationSeconds: 221,
            coverImageUrl: '/images/songs/song-5.jpg',
            audioUrl: '/audio/song-5.mp3',
            playCount: 180000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Dancing on Saturn',
            artistName: 'Luna Park',
            albumName: 'Cosmic Journey',
            durationSeconds: 256,
            coverImageUrl: '/images/songs/song-6.jpg',
            audioUrl: '/audio/song-6.mp3',
            playCount: 156000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Moonlight Melody',
            artistName: 'Luna Park',
            albumName: 'Cosmic Journey',
            durationSeconds: 243,
            coverImageUrl: '/images/songs/song-7.jpg',
            audioUrl: '/audio/song-7.mp3',
            playCount: 142000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Summer Nights',
            artistName: 'Luna Park',
            albumName: null,
            durationSeconds: 213,
            coverImageUrl: '/images/songs/song-8.jpg',
            audioUrl: '/audio/song-8.mp3',
            playCount: 23000,
            createdAt: new Date().toISOString(),
        },

        // DJ Nexus - Electronic (from "Pulse" album)
        {
            title: 'Electric Pulse',
            artistName: 'DJ Nexus',
            albumName: 'Pulse',
            durationSeconds: 289,
            coverImageUrl: '/images/songs/song-9.jpg',
            audioUrl: '/audio/song-9.mp3',
            playCount: 195000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Bass Drop Paradise',
            artistName: 'DJ Nexus',
            albumName: 'Pulse',
            durationSeconds: 278,
            coverImageUrl: '/images/songs/song-10.jpg',
            audioUrl: '/audio/song-10.mp3',
            playCount: 167000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Frequency Rising',
            artistName: 'DJ Nexus',
            albumName: 'Pulse',
            durationSeconds: 295,
            coverImageUrl: '/images/songs/song-11.jpg',
            audioUrl: '/audio/song-11.mp3',
            playCount: 145000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Neon Nights Remix',
            artistName: 'DJ Nexus',
            albumName: null,
            durationSeconds: 264,
            coverImageUrl: '/images/songs/song-12.jpg',
            audioUrl: '/audio/song-12.mp3',
            playCount: 31000,
            createdAt: new Date().toISOString(),
        },

        // Sarah Chen - Indie/Folk (from "Whispers in the Wind" album)
        {
            title: 'Morning Coffee',
            artistName: 'Sarah Chen',
            albumName: 'Whispers in the Wind',
            durationSeconds: 201,
            coverImageUrl: '/images/songs/song-13.jpg',
            audioUrl: '/audio/song-13.mp3',
            playCount: 78000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Autumn Leaves',
            artistName: 'Sarah Chen',
            albumName: 'Whispers in the Wind',
            durationSeconds: 234,
            coverImageUrl: '/images/songs/song-14.jpg',
            audioUrl: '/audio/song-14.mp3',
            playCount: 65000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Painted Sky',
            artistName: 'Sarah Chen',
            albumName: 'Whispers in the Wind',
            durationSeconds: 219,
            coverImageUrl: '/images/songs/song-15.jpg',
            audioUrl: '/audio/song-15.mp3',
            playCount: 54000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Rainy Day Blues',
            artistName: 'Sarah Chen',
            albumName: null,
            durationSeconds: 187,
            coverImageUrl: '/images/songs/song-16.jpg',
            audioUrl: '/audio/song-16.mp3',
            playCount: 8500,
            createdAt: new Date().toISOString(),
        },

        // The River Bend - Rock (from "Stone & Steel" album)
        {
            title: 'Thunder Road',
            artistName: 'The River Bend',
            albumName: 'Stone & Steel',
            durationSeconds: 276,
            coverImageUrl: '/images/songs/song-17.jpg',
            audioUrl: '/audio/song-17.mp3',
            playCount: 134000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Breaking Free',
            artistName: 'The River Bend',
            albumName: 'Stone & Steel',
            durationSeconds: 298,
            coverImageUrl: '/images/songs/song-18.jpg',
            audioUrl: '/audio/song-18.mp3',
            playCount: 118000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Wild Heart',
            artistName: 'The River Bend',
            albumName: 'Stone & Steel',
            durationSeconds: 265,
            coverImageUrl: '/images/songs/song-19.jpg',
            audioUrl: '/audio/song-19.mp3',
            playCount: 102000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Rebel Soul',
            artistName: 'The River Bend',
            albumName: null,
            durationSeconds: 254,
            coverImageUrl: '/images/songs/song-20.jpg',
            audioUrl: '/audio/song-20.mp3',
            playCount: 19000,
            createdAt: new Date().toISOString(),
        },

        // Marcus Cole - Hip-Hop (from "Urban Poetry" album)
        {
            title: 'Streets of Gold',
            artistName: 'Marcus Cole',
            albumName: 'Urban Poetry',
            durationSeconds: 237,
            coverImageUrl: '/images/songs/song-21.jpg',
            audioUrl: '/audio/song-21.mp3',
            playCount: 172000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Rise Up',
            artistName: 'Marcus Cole',
            albumName: 'Urban Poetry',
            durationSeconds: 243,
            coverImageUrl: '/images/songs/song-22.jpg',
            audioUrl: '/audio/song-22.mp3',
            playCount: 158000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'City Dreams',
            artistName: 'Marcus Cole',
            albumName: 'Urban Poetry',
            durationSeconds: 229,
            coverImageUrl: '/images/songs/song-23.jpg',
            audioUrl: '/audio/song-23.mp3',
            playCount: 139000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Hustle Hard',
            artistName: 'Marcus Cole',
            albumName: null,
            durationSeconds: 218,
            coverImageUrl: '/images/songs/song-24.jpg',
            audioUrl: '/audio/song-24.mp3',
            playCount: 27000,
            createdAt: new Date().toISOString(),
        },

        // Violet Storm - Pop/Rock (from "Electric Soul" album)
        {
            title: 'Purple Lightning',
            artistName: 'Violet Storm',
            albumName: 'Electric Soul',
            durationSeconds: 252,
            coverImageUrl: '/images/songs/song-25.jpg',
            audioUrl: '/audio/song-25.mp3',
            playCount: 143000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Fire in My Veins',
            artistName: 'Violet Storm',
            albumName: 'Electric Soul',
            durationSeconds: 267,
            coverImageUrl: '/images/songs/song-26.jpg',
            audioUrl: '/audio/song-26.mp3',
            playCount: 128000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Unbreakable',
            artistName: 'Violet Storm',
            albumName: 'Electric Soul',
            durationSeconds: 244,
            coverImageUrl: '/images/songs/song-27.jpg',
            audioUrl: '/audio/song-27.mp3',
            playCount: 115000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Phoenix Rising',
            artistName: 'Violet Storm',
            albumName: null,
            durationSeconds: 233,
            coverImageUrl: '/images/songs/song-28.jpg',
            audioUrl: '/audio/song-28.mp3',
            playCount: 12000,
            createdAt: new Date().toISOString(),
        },

        // The Harmony Project - Indie (from "Soundscapes" album)
        {
            title: 'Canvas of Sound',
            artistName: 'The Harmony Project',
            albumName: 'Soundscapes',
            durationSeconds: 287,
            coverImageUrl: '/images/songs/song-29.jpg',
            audioUrl: '/audio/song-29.mp3',
            playCount: 45000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Wavelength',
            artistName: 'The Harmony Project',
            albumName: 'Soundscapes',
            durationSeconds: 274,
            coverImageUrl: '/images/songs/song-30.jpg',
            audioUrl: '/audio/song-30.mp3',
            playCount: 38000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Symphony of Colors',
            artistName: 'The Harmony Project',
            albumName: 'Soundscapes',
            durationSeconds: 296,
            coverImageUrl: '/images/songs/song-31.jpg',
            audioUrl: '/audio/song-31.mp3',
            playCount: 32000,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Ethereal Journey',
            artistName: 'The Harmony Project',
            albumName: null,
            durationSeconds: 258,
            coverImageUrl: '/images/songs/song-32.jpg',
            audioUrl: '/audio/song-32.mp3',
            playCount: 4200,
            createdAt: new Date().toISOString(),
        },

        // Additional singles for variety
        {
            title: 'Lost in Translation',
            artistName: 'Sarah Chen',
            albumName: null,
            durationSeconds: 211,
            coverImageUrl: '/images/songs/song-33.jpg',
            audioUrl: '/audio/song-33.mp3',
            playCount: 6800,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Midnight Drive',
            artistName: 'The Midnight Echo',
            albumName: null,
            durationSeconds: 249,
            coverImageUrl: '/images/songs/song-34.jpg',
            audioUrl: '/audio/song-34.mp3',
            playCount: 18500,
            createdAt: new Date().toISOString(),
        },
        {
            title: 'Golden Hour',
            artistName: 'Luna Park',
            albumName: null,
            durationSeconds: 227,
            coverImageUrl: '/images/songs/song-35.jpg',
            audioUrl: '/audio/song-35.mp3',
            playCount: 21000,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(songs).values(sampleSongs);
    
    console.log('✅ Songs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});